format = """
$directory\
$git_branch\
$jobs\
$python\
$cmd_duration\
$character\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Configure directory settings
[directory]
style = "blue"
read_only = " ó°Œ¾"

# Configure running jobs view
[jobs]
symbol = "ï€“ "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

# Push items to right-sideof terminal
# [fill]
# symbol = " "

# Replace the 'â¯' symbol in the prompt with 'âœ', 'â†ª'
[character]
success_symbol = '[âœ](bold green) ' 
error_symbol = '[âœ](bold red) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
style = "yellow bold"
symbol = "ğŸ"
format = "[(\\($symbol $virtualenv\\) )]($style)"
